=== 0xJWLabs/tacky-borders/schema_test.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "UserConfig",
  "description": "Stores the complete configuration including global rules, window rules, and keybindings.",
  "type": "object",
  "properties": {
    "global": {
      "description": "Global settings applied across all windows.",
      "$ref": "#/$defs/GlobalRuleConfig"
    },
    "keybindings": {
      "description": "Application keybindings.",
      "$ref": "#/$defs/Keybindings"
    },
    "monitor_config_changes": {
      "description": "Enables monitoring for changes in the configuration file.",
      "type": "boolean",
      "default": false
    },
    "theme": {
      "description": "Enable custom predefined theme",
      "type": [
        "string",
        "null"
      ],
      "default": null
    },
    "window_rules": {
      "description": "Specific rules for individual windows.",
      "type": "array",
      "items": {
        "$ref": "#/$defs/WindowRuleConfig"
      }
    }
  },
  "$defs": {
    "AnimationConfig": {
      "type": "object",
      "properties": {
        "duration": {
          "anyOf": [
            {
              "$ref": "#/$defs/Duration"
            },
            {
              "type": "null"
            }
          ]
        },
        "easing": {
          "type": [
            "string",
            "null"
          ]
        },
        "kind": {
          "type": "string"
        }
      },
      "required": [
        "kind"
      ]
    },
    "AnimationsConfig": {
      "type": "object",
      "properties": {
        "active": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/$defs/AnimationConfig"
          }
        },
        "fps": {
          "type": [
            "integer",
            "null"
          ],
          "format": "int32"
        },
        "inactive": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/$defs/AnimationConfig"
          }
        }
      }
    },
    "BorderOffset": {
      "description": "Defines options for border offset customization",
      "oneOf": [
        {
          "type": "integer",
          "format": "int32",
          "description": "An integer representing the border offset in pixels. Positive values expand the border, negative values shrink it."
        },
        {
          "type": "string",
          "pattern": "^-?\\d+(px)?$",
          "description": "A string representing the border offset in pixels with a 'px' suffix (e.g., '5px' or '-5px'). Positive values expand, negative values shrink the border."
        }
      ]
    },
    "BorderWidth": {
      "description": "Defines options for border width customization",
      "oneOf": [
        {
          "type": "integer",
          "format": "int32",
          "description": "An integer representing the border width in pixels. Positive values expand the border, negative values shrink it."
        },
        {
          "type": "string",
          "pattern": "^-?\\d+(px)?$",
          "description": "A string representing the border width in pixels with a 'px' suffix (e.g., '5px' or '-5px'). Positive values expand, negative values shrink the border."
        }
      ]
    },
    "BorderStyle": {
      "description": "Defines options for border radius customization.",
      "oneOf": [
        {
          "description": "Fully rounded borders.",
          "type": "string",
          "const": "Round"
        },
        {
          "description": "Square borders with no rounding.",
          "type": "string",
          "const": "Square"
        },
        {
          "description": "Small rounding for subtle border effects.",
          "type": "string",
          "const": "SmallRound"
        },
        {
          "description": "Automatically determine the border radius based on context.",
          "type": "string",
          "const": "Auto"
        },
        {
          "description": "Custom border radius, specified in pixels.",
          "type": "object",
          "properties": {
            "Radius": {
              "type": "number",
              "format": "float"
            }
          },
          "additionalProperties": false,
          "required": [
            "Radius"
          ]
        }
      ]
    },
    "ColorMapping": {
      "description": "A structure that defines a gradient mapping, which contains a list of color stops and a direction.",
      "type": "object",
      "properties": {
        "colors": {
          "description": "A list of colors in the gradient, represented as hexadecimal color strings.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "direction": {
          "description": "The direction of the gradient, represented as a `GradientDirection`.",
          "$ref": "#/$defs/GradientDirection"
        }
      },
      "required": [
        "colors",
        "direction"
      ]
    },
    "Duration": {
      "description": "Represents a duration, which can be either a finite number (f32) or a non-empty string.",
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "Number": {
              "type": "number",
              "format": "float"
            }
          },
          "additionalProperties": false,
          "required": [
            "Number"
          ]
        },
        {
          "type": "object",
          "properties": {
            "Text": {
              "type": "string"
            }
          },
          "additionalProperties": false,
          "required": [
            "Text"
          ]
        }
      ]
    },
    "GlobalColor": {
      "description": "The `GlobalColor` enum represents a global color that can be either a color string (e.g., a hex color code or a color name)\n or a mapping to a gradient definition.",
      "anyOf": [
        {
          "description": "A string representing a color, which could be a hex color code or a color name.\n\n This variant is used for basic color definitions like `\"#FF5733\"` or `\"red\"`.",
          "type": "string"
        },
        {
          "description": "A mapping defining a gradient color.\n\n This variant is used when the color is a gradient and contains a `ColorMapping` to define the gradient's\n color stops, direction, and other properties.",
          "$ref": "#/$defs/ColorMapping"
        }
      ]
    },
    "GlobalRuleConfig": {
      "description": "Contains global configuration settings applied across all windows.",
      "type": "object",
      "properties": {
        "active_color": {
          "description": "Default color for active window borders.",
          "$ref": "#/$defs/GlobalColor"
        },
        "animations": {
          "description": "Animation settings for borders.",
          "$ref": "#/$defs/AnimationsConfig"
        },
        "border_offset": {
          "description": "Default offset for the window borders.",
          "$ref": "#/defs/BorderOffset",
          "default": -1
        },
        "border_style": {
          "description": "Default border radius settings.",
          "$ref": "#/$defs/BorderStyle"
        },
        "border_width": {
          "description": "Default width of the window borders.",
          "$ref": "#/defs/BorderWidth",
          "default": 2
        },
        "inactive_color": {
          "description": "Default color for inactive window borders.",
          "$ref": "#/$defs/GlobalColor"
        },
        "initialize_delay": {
          "description": "Delay (in milliseconds) before applying borders after initialization.",
          "type": "integer",
          "format": "uint64",
          "default": 250,
          "minimum": 0
        },
        "unminimize_delay": {
          "description": "Delay (in milliseconds) before applying borders after unminimizing.",
          "type": "integer",
          "format": "uint64",
          "default": 200,
          "minimum": 0
        }
      }
    },
    "GradientCoordinates": {
      "type": "object",
      "properties": {
        "end": {
          "description": "The [x, y] coordinates for the end point of the gradient.",
          "type": "array",
          "items": {
            "type": "number",
            "format": "float"
          },
          "maxItems": 2,
          "minItems": 2
        },
        "start": {
          "description": "The [x, y] coordinates for the start point of the gradient.",
          "type": "array",
          "items": {
            "type": "number",
            "format": "float"
          },
          "maxItems": 2,
          "minItems": 2
        }
      },
      "required": [
        "start",
        "end"
      ]
    },
    "GradientDirection": {
      "description": "Enum representing different types of gradient directions.\n It can either be a string describing the direction (e.g., \"to right\") or explicit coordinates for the gradient direction.",
      "anyOf": [
        {
          "description": "Direction is represented as a string (e.g., \"to right\").",
          "type": "string"
        },
        {
          "description": "Direction is represented as coordinates (e.g., GradientCoordinates).",
          "$ref": "#/$defs/GradientCoordinates"
        }
      ]
    },
    "Keybindings": {
      "type": "object",
      "properties": {
        "exit": {
          "type": "string",
          "default": "f10"
        },
        "open_config": {
          "type": "string",
          "default": "f9"
        },
        "reload": {
          "type": "string",
          "default": "f8"
        }
      }
    },
    "MatchKind": {
      "description": "Specifies the type of match used for window identification.",
      "oneOf": [
        {
          "description": "Match based on the window title.",
          "type": "string",
          "const": "Title"
        },
        {
          "description": "Match based on the class name of the window.",
          "type": "string",
          "const": "Class"
        },
        {
          "description": "Match based on the process name or executable associated with the window.",
          "type": "string",
          "const": "Process"
        }
      ]
    },
    "MatchStrategy": {
      "description": "Defines the strategy for matching a value against a criterion.",
      "oneOf": [
        {
          "description": "Match values that are exactly equal.",
          "type": "string",
          "const": "Equals"
        },
        {
          "description": "Match values using a regular expression.",
          "type": "string",
          "const": "Regex"
        },
        {
          "description": "Match values that contain the specified substring.",
          "type": "string",
          "const": "Contains"
        }
      ]
    },
    "WindowMatchConfig": {
      "description": "Represents criteria used to match windows for applying specific configurations.",
      "type": "object",
      "properties": {
        "active_color": {
          "description": "Color for the border when the window is active.",
          "anyOf": [
            {
              "$ref": "#/$defs/GlobalColor"
            },
            {
              "type": "null"
            }
          ]
        },
        "animations": {
          "description": "Animation settings for the window borders.",
          "anyOf": [
            {
              "$ref": "#/$defs/AnimationsConfig"
            },
            {
              "type": "null"
            }
          ]
        },
        "border_offset": {
          "description": "Offset of the border relative to the window.",
          "anyOf": [
            {
              "$ref": "#/defs/BorderOffset"
            },
            {
              "type": null
            }
          ]
        },
        "border_style": {
          "description": "Radius of the border corners.",
          "anyOf": [
            {
              "$ref": "#/$defs/BorderStyle"
            },
            {
              "type": "null"
            }
          ]
        },
        "border_width": {
          "description": "Width of the border in pixels.",
          "anyOf": [
            {
              "$ref": "#/defs/BorderWidth"
            },
            {
              "type": "null"
            }
          ]
        },
        "enabled": {
          "description": "Whether borders are enabled for this match.",
          "type": [
            "boolean",
            "null"
          ]
        },
        "inactive_color": {
          "description": "Color for the border when the window is inactive.",
          "anyOf": [
            {
              "$ref": "#/$defs/GlobalColor"
            },
            {
              "type": "null"
            }
          ]
        },
        "initialize_delay": {
          "description": "Delay (in milliseconds) before applying the border after initialization.",
          "type": [
            "integer",
            "null"
          ],
          "format": "uint64",
          "minimum": 0
        },
        "kind": {
          "description": "Type of match (e.g., title, class, or process).",
          "anyOf": [
            {
              "$ref": "#/$defs/MatchKind"
            },
            {
              "type": "null"
            }
          ]
        },
        "strategy": {
          "description": "Strategy for matching, such as exact match or regex.",
          "anyOf": [
            {
              "$ref": "#/$defs/MatchStrategy"
            },
            {
              "type": "null"
            }
          ]
        },
        "unminimize_delay": {
          "description": "Delay (in milliseconds) before applying the border after unminimizing.",
          "type": [
            "integer",
            "null"
          ],
          "format": "uint64",
          "minimum": 0
        },
        "value": {
          "description": "The value to match against (e.g., window title or class name).",
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "WindowRuleConfig": {
      "description": "Represents a rule for a specific window, including matching criteria and associated actions.",
      "type": "object",
      "properties": {
        "match": {
          "description": "The matching details and settings for a specific type of window.",
          "$ref": "#/$defs/WindowMatchConfig"
        }
      },
      "required": [
        "match"
      ]
    }
  }
}

=== 0xJWLabs/tacky-borders/resources/config.json
{
  "$schema": "https://raw.githubusercontent.com/GlazeBar/tacky-borders/refs/heads/main/schema.json",
  "monitor_config_changes": true,
  "keybindings": {
    "reload": "f8",
    "open_config": "f9",
    "exit": "f10"
  },
  "global": {
    "border_width": 2,
    "border_offset": -1,
    "border_style": "Auto",
    "active_color": {
      "colors": [
        "#000000",
        "#ffffff"
      ],
      "direction": {
        "start": [
          0.0,
          0.0
        ],
        "end": [
          1.0,
          0.0
        ]
      }
    },
    "inactive_color": "#d2d2d2",
    "animations": {
      "active": [
        {
          "kind": "fade",
          "duration": "450ms",
          "easing": "EaseInOut"
        },
        {
          "kind": "spiral",
          "duration": "1800ms",
          "easing": "cubic-bezier(0.42, 0.0, 0.58, 1.0)"
        }
      ],
      "inactive": [
        {
          "kind": "fade",
          "duration": "450ms",
          "easing": "ease-in-out"
        },
        {
          "kind": "reverse_spiral",
          "duration": "1800ms",
          "easing": "cubic-bezier(0.42, 0.0, 0.58, 1.0)"
        }
      ],
      "fps": 60
    },
    "initialize_delay": 150,
    "restore_delay": 100
  },
  "window_rules": [
    {
      "match": {
        "kind": "Class",
        "value": "Windows.UI.Core.CoreWindow",
        "strategy": "Contains",
        "enabled": false
      }
    },
    {
      "match": {
        "kind": "Process",
        "value": "(?i)^Flow.*",
        "strategy": "Regex",
        "enabled": false
      }
    },
    {
      "match": {
        "kind": "Title",
        "value": "Zebar",
        "strategy": "Equals",
        "enabled": false
      }
    }
  ]
}
